# Generated by Django 2.2.5 on 2020-02-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
