# Generated by Django 2.2.5 on 2020-03-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_sport', models.TextField(max_length=200000)),
                ('date_posted_sport', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
